# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-17 21:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import perma_payments.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutgoingTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_uuid', models.UUIDField(default=uuid.uuid4, help_text="A unique ID for this 'transaction'. Intended to protect against duplicate transactions.")),
                ('request_datetime', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('ACCEPT', 'ACCEPT'), ('REVIEW', 'REVIEW'), ('DECLINE', 'DECLINE'), ('ERROR', 'ERROR'), ('CANCEL', 'CANCEL')], max_length=7, null=True)),
                ('reason_code', models.IntegerField(null=True)),
                ('message', models.TextField(null=True)),
                ('full_response', models.BinaryField(help_text='The full response, encrypted, in case we ever need it.', null=True)),
                ('encryption_key_id', models.IntegerField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubscriptionAgreement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registrar', models.IntegerField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Rejected', 'Rejected'), ('Aborted', 'Aborted'), ('Cancelled', 'Cancelled'), ('Completed', 'Completed'), ('Current', 'Current'), ('Hold', 'Hold'), ('Superseded', 'Superseded')], max_length=20)),
                ('status_updated', models.DateTimeField(auto_now=True)),
                ('cancellation_requested', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionRequest',
            fields=[
                ('outgoingtransaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='perma_payments.OutgoingTransaction')),
                ('reference_number', models.CharField(default=perma_payments.models.generate_reference_number, help_text="Unqiue ID for this subscription. Subsequent charges, automatically made byCyberSource onthe recurring schedule, will all be associated with this reference number. Called 'Merchant Reference Number' in CyberSource Business Center.", max_length=32)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount to be charged immediately', max_digits=19)),
                ('recurring_amount', models.DecimalField(decimal_places=2, help_text='Amount to be charged repeatedly, beginning on recurring_start_date', max_digits=19)),
                ('recurring_frequency', models.CharField(choices=[('weekly', 'weekly'), ('bi-weekly', 'bi-weekly'), ('quad-weekly', 'quad-weekly'), ('monthly', 'monthly'), ('semi-monthly', 'semi-monthly'), ('quarterly', 'quarterly'), ('semi-annually', 'semi-annually'), ('annually', 'annually')], max_length=20)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('locale', models.CharField(default='en-us', max_length=5)),
                ('payment_method', models.CharField(default='card', max_length=30)),
                ('transaction_type', models.CharField(default='sale,create_payment_token', max_length=30)),
                ('subscription_agreement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_request', to='perma_payments.SubscriptionAgreement')),
            ],
            options={
                'abstract': False,
            },
            bases=('perma_payments.outgoingtransaction',),
        ),
        migrations.CreateModel(
            name='SubscriptionRequestResponse',
            fields=[
                ('response_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='perma_payments.Response')),
                ('payment_token', models.CharField(blank=True, default='', max_length=26)),
                ('subscription_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_request_response', to='perma_payments.SubscriptionRequest')),
            ],
            options={
                'abstract': False,
            },
            bases=('perma_payments.response',),
        ),
        migrations.CreateModel(
            name='UpdateRequest',
            fields=[
                ('outgoingtransaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='perma_payments.OutgoingTransaction')),
                ('transaction_type', models.CharField(default='update_payment_token', max_length=30)),
                ('subscription_agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='update_request', to='perma_payments.SubscriptionAgreement')),
            ],
            options={
                'abstract': False,
            },
            bases=('perma_payments.outgoingtransaction',),
        ),
        migrations.AddField(
            model_name='response',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_perma_payments.response_set+', to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='outgoingtransaction',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_perma_payments.outgoingtransaction_set+', to='contenttypes.ContentType'),
        ),
    ]
