# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-02 18:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perma_payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionagreement',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Rejected', 'Rejected'), ('Abandoned', 'Abandoned'), ('Cancelled', 'Cancelled'), ('Completed', 'Completed'), ('Current', 'Current'), ('Hold', 'Hold'), ('Superseded', 'Superseded')], max_length=20),
        ),
    ]
