# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-02 18:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perma_payments', '0002_auto_20170802_1833'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionRequestResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('ACCEPT', 'ACCEPT'), ('REVIEW', 'REVIEW'), ('DECLINE', 'DECLINE'), ('ERROR', 'ERROR'), ('CANCEL', 'CANCEL')], max_length=7)),
                ('reason_code', models.IntegerField()),
                ('message', models.TextField()),
                ('payment_token', models.CharField(blank=True, default='', max_length=26)),
                ('full_response', models.TextField(help_text='The full response, encrypted, in case we ever need it.')),
                ('subscription_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_request', to='perma_payments.SubscriptionRequest')),
            ],
        ),
    ]
