# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-05 16:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perma_payments', '0003_auto_20170818_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionrequest',
            name='recurring_start_date',
            field=models.DateField(default=datetime.date(1970, 1, 1), help_text='Date on which to commence charging recurring_amount'),
            preserve_default=False,
        ),
    ]
