# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-13 14:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perma_payments', '0004_subscriptionrequest_recurring_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='decision',
            field=models.CharField(blank=True, choices=[('ACCEPT', 'ACCEPT'), ('REVIEW', 'REVIEW'), ('DECLINE', 'DECLINE'), ('ERROR', 'ERROR'), ('CANCEL', 'CANCEL')], max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='response',
            name='encryption_key_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='response',
            name='full_response',
            field=models.BinaryField(help_text='The full response, encrypted, in case we ever need it.'),
        ),
        migrations.AlterField(
            model_name='response',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='response',
            name='reason_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
