# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-26 19:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import perma_payments.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('perma_payments', '0005_auto_20170913_1439'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalSubscriptionAgreement',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('registrar', models.IntegerField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Rejected', 'Rejected'), ('Aborted', 'Aborted'), ('Cancelled', 'Cancelled'), ('Completed', 'Completed'), ('Current', 'Current'), ('Hold', 'Hold'), ('Superseded', 'Superseded')], max_length=20)),
                ('status_updated', models.DateTimeField(blank=True, editable=False)),
                ('cancellation_requested', models.BooleanField(default=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'get_latest_by': 'history_date',
                'verbose_name': 'historical subscription agreement',
                'ordering': ('-history_date', '-history_id'),
            },
        ),
        migrations.AlterField(
            model_name='subscriptionrequest',
            name='reference_number',
            field=models.CharField(default=perma_payments.models.generate_reference_number, help_text="Unqiue ID for this subscription. Subsequent charges, automatically made by CyberSource on the recurring schedule, will all be associated with this reference number. Called 'Merchant Reference Number' in CyberSource Business Center.", max_length=32),
        ),
    ]
