# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-14 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perma_payments', '0006_auto_20170803_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionagreement',
            name='cancellation_requested',
            field=models.BooleanField(default=False),
        ),
    ]
