# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-16 15:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('perma_payments', '0007_subscriptionagreement_cancellation_requested'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpdateRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_datetime', models.DateTimeField(auto_now_add=True)),
                ('transaction_uuid', models.UUIDField(default=uuid.uuid4, help_text="A unique ID for this 'transaction'. Intended to protect against duplicate transactions.")),
                ('transaction_type', models.CharField(default='update_payment_token', max_length=30)),
                ('subscription_agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='update_request', to='perma_payments.SubscriptionAgreement')),
            ],
        ),
        migrations.AlterField(
            model_name='subscriptionrequest',
            name='subscription_agreement',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_request', to='perma_payments.SubscriptionAgreement'),
        ),
        migrations.AlterField(
            model_name='subscriptionrequestresponse',
            name='subscription_request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_request_response', to='perma_payments.SubscriptionRequest'),
        ),
    ]
