# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-26 20:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perma_payments', '0008_auto_20170926_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updaterequest',
            name='subscription_agreement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='update_requests', to='perma_payments.SubscriptionAgreement'),
        ),
    ]
