# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-17 14:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion

def make_sub_request_transactions(apps, schema_editor):
    OutgoingTransaction = apps.get_model('perma_payments', 'OutgoingTransaction')
    SubscriptionRequest = apps.get_model('perma_payments', 'SubscriptionRequest')
    ContentType = apps.get_model('contenttypes', 'ContentType')
    new_ct = ContentType.objects.get_for_model(SubscriptionRequest)
    for request in SubscriptionRequest.objects.all():
        o = OutgoingTransaction(
            polymorphic_ctype=new_ct
        )
        o.save()
        request.outgoingtransaction_ptr = o
        request.save()

def save_relationships(apps, schema_editor):
    SubscriptionRequest = apps.get_model('perma_payments', 'SubscriptionRequest')
    for request in SubscriptionRequest.objects.all():
        request.temp = request.subscription_request_response.pk
        request.save()

def restore_relationships(apps, schema_editor):
    SubscriptionRequest = apps.get_model('perma_payments', 'SubscriptionRequest')
    SubscriptionRequestResponse = apps.get_model('perma_payments', 'SubscriptionRequestResponse')
    for request in SubscriptionRequest.objects.all():
        request.subscription_request_response = SubscriptionRequestResponse.objects.get(id=request.temp)
        request.save()

def make_update_request_transactions(apps, schema_editor):
    OutgoingTransaction = apps.get_model('perma_payments', 'OutgoingTransaction')
    UpdateRequest = apps.get_model('perma_payments', 'UpdateRequest')
    ContentType = apps.get_model('contenttypes', 'ContentType')
    new_ct = ContentType.objects.get_for_model(UpdateRequest)
    for request in UpdateRequest.objects.all():
        o = OutgoingTransaction(
            polymorphic_ctype=new_ct
        )
        o.save()
        request.outgoingtransaction_ptr = o
        request.save()


class Migration(migrations.Migration):

    dependencies = [
        ('perma_payments', '0009_outgoingtransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionrequest',
            name='outgoingtransaction_ptr',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='perma_payments.OutgoingTransaction'),
        ),
        migrations.RunPython(make_sub_request_transactions, migrations.RunPython.noop),
        migrations.AddField(
            model_name='subscriptionrequest',
            name='temp',
            field=models.IntegerField(null=True),
        ),
        migrations.RunPython(save_relationships, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='subscriptionrequest',
            name='id',
        ),
        migrations.AlterField(
            model_name='subscriptionrequest',
            name='outgoingtransaction_ptr',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='perma_payments.OutgoingTransaction'),
        ),
        migrations.RunPython(restore_relationships, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='subscriptionrequest',
            name='temp',
        ),
        migrations.AlterField(
            model_name='subscriptionrequest',
            name='outgoingtransaction_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='perma_payments.OutgoingTransaction'),
        ),
        migrations.AddField(
            model_name='updaterequest',
            name='outgoingtransaction_ptr',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='perma_payments.OutgoingTransaction'),
        ),
        migrations.RunPython(make_update_request_transactions, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='updaterequest',
            name='id',
        ),
        migrations.AlterField(
            model_name='updaterequest',
            name='outgoingtransaction_ptr',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='perma_payments.OutgoingTransaction'),
        ),
    ]
