# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-14 20:57
from __future__ import unicode_literals

from django.db import migrations, models
import perma_payments.models


class Migration(migrations.Migration):

    dependencies = [
        ('perma_payments', '0010_auto_20171102_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsubscriptionagreement',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Rejected', 'Rejected'), ('Aborted', 'Aborted'), ('Canceled', 'Canceled'), ('Completed', 'Completed'), ('Current', 'Current'), ('Hold', 'Hold'), ('Superseded', 'Superseded')], max_length=20),
        ),
        migrations.AlterField(
            model_name='subscriptionagreement',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Rejected', 'Rejected'), ('Aborted', 'Aborted'), ('Canceled', 'Canceled'), ('Completed', 'Completed'), ('Current', 'Current'), ('Hold', 'Hold'), ('Superseded', 'Superseded')], max_length=20),
        ),
        migrations.AlterField(
            model_name='subscriptionrequest',
            name='reference_number',
            field=models.CharField(default=perma_payments.models.generate_reference_number, help_text="Unique ID for this subscription. Subsequent charges, automatically made by CyberSource on the recurring schedule, will all be associated with this reference number. Called 'Merchant Reference Number' in CyberSource Business Center.", max_length=32),
        ),
    ]
