# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-17 19:50
from __future__ import unicode_literals

from django.db import migrations, models
import uuid

def transfer_data(apps, schema_editor):
    SubscriptionRequest = apps.get_model('perma_payments', 'SubscriptionRequest')
    UpdateRequest = apps.get_model('perma_payments', 'UpdateRequest')
    for request in SubscriptionRequest.objects.all():
        request.n_request_datetime = request.request_datetime
        request.n_transaction_uuid = request.transaction_uuid
        request.save()
    for request in UpdateRequest.objects.all():
        request.n_request_datetime = request.request_datetime
        request.n_transaction_uuid = request.transaction_uuid
        request.save()


class Migration(migrations.Migration):

    dependencies = [
        ('perma_payments', '0010_polymorphic_requests'),
    ]

    operations = [
        migrations.AddField(
            model_name='outgoingtransaction',
            name='n_request_datetime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='outgoingtransaction',
            name='n_transaction_uuid',
            field=models.UUIDField(default=uuid.uuid4, help_text="A unique ID for this 'transaction'. Intended to protect against duplicate transactions."),
        ),
        migrations.RunPython(transfer_data, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='subscriptionrequest',
            name='request_datetime',
        ),
        migrations.RemoveField(
            model_name='subscriptionrequest',
            name='transaction_uuid',
        ),
        migrations.RemoveField(
            model_name='updaterequest',
            name='request_datetime',
        ),
        migrations.RemoveField(
            model_name='updaterequest',
            name='transaction_uuid',
        ),
        migrations.RenameField(
            model_name='outgoingtransaction',
            old_name='n_request_datetime',
            new_name='request_datetime',
        ),
        migrations.RenameField(
            model_name='outgoingtransaction',
            old_name='n_transaction_uuid',
            new_name='transaction_uuid',
        ),
        migrations.RenameField(
            model_name='outgoingtransaction',
            old_name='n_request_datetime',
            new_name='request_datetime',
        ),
        migrations.RenameField(
            model_name='outgoingtransaction',
            old_name='n_transaction_uuid',
            new_name='transaction_uuid',
        ),
    ]
