# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-17 20:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perma_payments', '0011_move_shared_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updaterequest',
            name='outgoingtransaction_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='perma_payments.OutgoingTransaction'),
        ),
    ]
