# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-28 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perma_payments', '0011_auto_20171114_2057'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalsubscriptionagreement',
            old_name='registrar',
            new_name='customer_pk',
        ),
        migrations.RenameField(
            model_name='subscriptionagreement',
            old_name='registrar',
            new_name='customer_pk',
        ),
        migrations.AddField(
            model_name='historicalsubscriptionagreement',
            name='customer_type',
            field=models.CharField(choices=[('Registrar', 'Registrar'), ('Individual', 'Individual')], default='Registrar', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscriptionagreement',
            name='customer_type',
            field=models.CharField(choices=[('Registrar', 'Registrar'), ('Individual', 'Individual')], default='Registrar', max_length=20),
            preserve_default=False,
        ),
    ]
