# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-17 20:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion

def make_responses(apps, schema_editor):
    Response = apps.get_model('perma_payments', 'Response')
    SubscriptionRequestResponse = apps.get_model('perma_payments', 'SubscriptionRequestResponse')
    ContentType = apps.get_model('contenttypes', 'ContentType')
    new_ct = ContentType.objects.get_for_model(SubscriptionRequestResponse)
    for r in SubscriptionRequestResponse.objects.all():
        o = Response(
            polymorphic_ctype=new_ct
        )
        o.save()
        r.response_ptr = o
        r.save()


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('perma_payments', '0012_auto_20170817_2014'),
    ]

    operations = [
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_decision', models.CharField(choices=[('ACCEPT', 'ACCEPT'), ('REVIEW', 'REVIEW'), ('DECLINE', 'DECLINE'), ('ERROR', 'ERROR'), ('CANCEL', 'CANCEL')], max_length=7, null=True)),
                ('n_reason_code', models.IntegerField(null=True)),
                ('n_message', models.TextField(null=True)),
                ('n_full_response', models.BinaryField(help_text='The full response, encrypted, in case we ever need it.', null=True)),
                ('n_encryption_key_id', models.IntegerField(null=True)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_perma_payments.response_set+', to='contenttypes.ContentType')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='subscriptionrequestresponse',
            name='response_ptr',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='perma_payments.Response'),
        ),
        migrations.RunPython(make_responses, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='subscriptionrequestresponse',
            name='id',
        ),
        migrations.AlterField(
            model_name='subscriptionrequestresponse',
            name='response_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='perma_payments.Response'),
        ),
    ]
