# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-17 20:43
from __future__ import unicode_literals

from django.db import migrations

def transfer_data(apps, schema_editor):
    SubscriptionRequestResponse = apps.get_model('perma_payments', 'SubscriptionRequestResponse')
    for r in SubscriptionRequestResponse.objects.all():
        r.n_decision = r.decision
        r.n_reason_code = r.reason_code
        r.n_message = r.message
        r.n_full_response = r.full_response
        r.n_encryption_key_id = r.encryption_key_id
        r.save()


class Migration(migrations.Migration):

    dependencies = [
        ('perma_payments', '0013_polymorphic_responses'),
    ]

    operations = [
        migrations.RunPython(transfer_data, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='subscriptionrequestresponse',
            name='decision',
        ),
        migrations.RemoveField(
            model_name='subscriptionrequestresponse',
            name='encryption_key_id',
        ),
        migrations.RemoveField(
            model_name='subscriptionrequestresponse',
            name='full_response',
        ),
        migrations.RemoveField(
            model_name='subscriptionrequestresponse',
            name='message',
        ),
        migrations.RemoveField(
            model_name='subscriptionrequestresponse',
            name='reason_code',
        ),
        migrations.RenameField(
            model_name='response',
            old_name='n_decision',
            new_name='decision',
        ),
        migrations.RenameField(
            model_name='response',
            old_name='n_encryption_key_id',
            new_name='encryption_key_id',
        ),
        migrations.RenameField(
            model_name='response',
            old_name='n_full_response',
            new_name='full_response',
        ),
        migrations.RenameField(
            model_name='response',
            old_name='n_message',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='response',
            old_name='n_reason_code',
            new_name='reason_code',
        ),
    ]
