# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-29 21:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('perma_payments', '0014_auto_20181127_1631'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='changerequest',
            name='recurring_frequency',
        ),
        migrations.RemoveField(
            model_name='changerequest',
            name='recurring_start_date',
        ),
        migrations.AddField(
            model_name='changerequest',
            name='link_limit_effective_timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='For internal use only: when Perma should apply the new link limit associated with this purchase'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalsubscriptionagreement',
            name='current_link_limit_effective_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionagreement',
            name='current_link_limit_effective_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionrequest',
            name='link_limit_effective_timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='For internal use only: when Perma should apply the new link limit associated with this purchase'),
            preserve_default=False,
        ),
    ]
