# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-07 17:41
from __future__ import unicode_literals

from django.db import migrations


def handle_existing_subscriptions(apps, schema_editor):
    """
    Populate the new SubscriptionAgreement fields where appropriate
    """
    SubscriptionAgreement = apps.get_model('perma_payments', 'SubscriptionAgreement')
    subscriptions_ever_current = SubscriptionAgreement.objects.filter(
        status__in=[
            'Canceled',
            'Completed',
            'Current',
            'Hold',
            'Superseded'
        ]
    )
    for sa in subscriptions_ever_current:
        # get these fields' values from the subscription request,
        # like happens now upon receiving CyberSource's callback
        sa.current_link_limit = sa.subscription_request.link_limit
        sa.current_frequency = sa.subscription_request.recurring_frequency
        sa.current_rate = sa.subscription_request.recurring_amount
        # use the subscription agreement's creation date as a proxy for this
        sa.current_link_limit_effective_timestamp = sa.created_date
        sa.save()


class Migration(migrations.Migration):

    dependencies = [
        ('perma_payments', '0015_auto_20181129_2148'),
    ]

    operations = [
        migrations.RunPython(handle_existing_subscriptions, migrations.RunPython.noop),
    ]
