# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-24 16:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import perma_payments.models


class Migration(migrations.Migration):

    dependencies = [
        ('perma_payments', '0016_populate_new_sa_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseRequest',
            fields=[
                ('outgoingtransaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='perma_payments.OutgoingTransaction')),
                ('customer_pk', models.IntegerField()),
                ('customer_type', models.CharField(choices=[('Registrar', 'Registrar'), ('Individual', 'Individual')], max_length=20)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('locale', models.CharField(default='en-us', max_length=5)),
                ('payment_method', models.CharField(default='card', max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount to be charged immediately', max_digits=19)),
                ('transaction_type', models.CharField(default='sale', max_length=30)),
                ('reference_number', models.CharField(default=perma_payments.models.generate_reference_number, help_text="Unique ID for this purchase. Called 'Merchant Reference Number' in CyberSource Business Center.", max_length=32)),
                ('link_quantity', models.PositiveIntegerField()),
            ],
            options={
                'manager_inheritance_from_future': True,
            },
            bases=('perma_payments.outgoingtransaction', models.Model),
        ),
        migrations.CreateModel(
            name='PurchaseRequestResponse',
            fields=[
                ('response_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='perma_payments.Response')),
                ('inform_perma', models.BooleanField(default=False, help_text='Should Perma be informed that this customer has successfully purchased more links?')),
                ('perma_acknowleged_at', models.DateTimeField(blank=True, null=True)),
                ('related_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_request_response', to='perma_payments.PurchaseRequest')),
            ],
            options={
                'manager_inheritance_from_future': True,
            },
            bases=('perma_payments.response',),
        ),
    ]
