"""
Tunnel management for payment provider testing.

This module provides utilities for running tunnels (ngrok, stripe CLI)
that allow external payment providers to send callbacks to local test servers.
"""

import re
import subprocess
import threading
import time
from pathlib import Path

# Path to managed settings file for tunnel secrets
SETTINGS_TUNNELS_FILE = Path(__file__).parent.parent.parent / 'config/settings/settings_tunnels.py'

# Fixed ports per provider - ensures late webhooks from one test don't hit
# the next test's server (they'll just fail to connect, which is fine)
PROVIDER_PORTS = {
    'stripe': 8700,
    'cybersource_rest': 8701,
    'cybersource_legacy': 8702,
}

def write_tunnel_settings(**kwargs):
    """
    Write tunnel-managed settings to settings_tunnels.py.
    
    This file is imported by settings.py to configure webhook secrets
    and other tunnel-dependent settings.
    
    Args:
        **kwargs: Settings to write, e.g., stripe_webhook_secret='whsec_...'
    """
    lines = [
        "# Auto-generated by tunnel commands. Do not edit manually.",
        "# This file is imported by settings.py",
        "",
    ]
    
    if 'stripe_webhook_secret' in kwargs:
        lines.append(f"STRIPE_WEBHOOK_SECRET = '{kwargs['stripe_webhook_secret']}'")
    
    if 'ngrok_url' in kwargs:
        lines.append(f"# ngrok URL: {kwargs['ngrok_url']}")
        lines.append(f"# CyberSource callback: {kwargs['ngrok_url']}/cybersource-callback/")
    
    lines.append("")
    
    SETTINGS_TUNNELS_FILE.write_text('\n'.join(lines))
    print(f"Updated {SETTINGS_TUNNELS_FILE}")


def is_stripe_tunnel_running() -> bool:
    """Check if stripe listen is currently running."""
    try:
        result = subprocess.run(
            ['pgrep', '-f', 'stripe listen'],
            capture_output=True,
            text=True
        )
        return result.returncode == 0
    except Exception:
        return False


def is_ngrok_running() -> bool:
    """Check if ngrok is currently running."""
    try:
        # Check ngrok's local API
        import urllib.request
        import json
        with urllib.request.urlopen("http://localhost:4040/api/tunnels", timeout=1) as response:
            data = json.loads(response.read())
            return len(data.get("tunnels", [])) > 0
    except Exception:
        return False


def get_ngrok_public_url() -> str | None:
    """Get the current ngrok public URL if running."""
    try:
        import urllib.request
        import json
        with urllib.request.urlopen("http://localhost:4040/api/tunnels", timeout=1) as response:
            data = json.loads(response.read())
            for tunnel in data.get("tunnels", []):
                if tunnel.get("proto") == "https":
                    return tunnel.get("public_url")
    except Exception:
        pass
    return None


class TunnelProcess:
    """
    Base class for managing tunnel subprocesses.
    
    Provides common functionality for streaming output and cleanup.
    """
    
    def __init__(self, cmd: list[str]):
        self.cmd = cmd
        self.proc = None
    
    def start(self):
        """Start the tunnel subprocess."""
        self.proc = subprocess.Popen(
            self.cmd,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            text=True,
            bufsize=1,
        )
        return self
    
    def stream_output(self, callback=None):
        """
        Stream output from the subprocess.
        
        Args:
            callback: Optional function to call for each line.
                      If it returns True, the interesting output has been found.
        """
        if not self.proc:
            raise RuntimeError("Tunnel not started")
        
        try:
            for line in self.proc.stdout:
                print(line, end='')
                if callback and callback(line):
                    callback = None  # Only call once
            self.proc.wait()
        except KeyboardInterrupt:
            print("\n>>> Stopping tunnel...")
            self.stop()
    
    def stop(self):
        """Stop the tunnel subprocess."""
        if self.proc:
            self.proc.terminate()
            try:
                self.proc.wait(timeout=5)
            except subprocess.TimeoutExpired:
                self.proc.kill()
    
    def is_running(self) -> bool:
        """Check if the subprocess is still running."""
        return self.proc is not None and self.proc.poll() is None


class StripeTunnel(TunnelProcess):
    """
    Stripe CLI webhook forwarding tunnel.
    
    Usage:
        tunnel = StripeTunnel()
        tunnel.start()
        tunnel.stream_output()  # Blocks until Ctrl+C
    """
    
    def __init__(self, forward_to: str = None, port: int = None):
        port = port or PROVIDER_PORTS['stripe']
        forward_to = forward_to or f"http://localhost:{port}/callback/stripe/"
        super().__init__(["stripe", "listen", "--forward-to", forward_to])
        self.forward_to = forward_to
        self.webhook_secret = None
    
    def start(self):
        print(f"Starting Stripe webhook forwarding to {self.forward_to}")
        print("Waiting for webhook secret...")
        print("(Press Ctrl+C to stop)\n")
        return super().start()
    
    def stream_output(self):
        """Stream output and capture webhook secret."""
        whsec_pattern = re.compile(r"(whsec_[A-Za-z0-9]+)")
        secret_found = False
        
        def on_line(line):
            nonlocal secret_found
            
            if not secret_found:
                match = whsec_pattern.search(line)
                if match:
                    self.webhook_secret = match.group(1)
                    secret_found = True
                    print(f"\n>>> Found webhook secret: {self.webhook_secret}")
                    write_tunnel_settings(stripe_webhook_secret=self.webhook_secret)
                    print(">>> Settings updated. You can now run tests in another terminal.")
                    print(">>> Keep this running to receive webhooks.\n")
                    return True
                
                if "not configured API keys" in line or "stripe login" in line.lower():
                    print("\n>>> ERROR: Stripe CLI not authenticated.")
                    print(">>> Run: stripe login")
                    self.stop()
            
            return False
        
        super().stream_output(on_line)


class NgrokTunnel(TunnelProcess):
    """
    ngrok HTTP tunnel for CyberSource Legacy callbacks.
    
    Usage:
        tunnel = NgrokTunnel()
        tunnel.start()
        tunnel.stream_output()  # Blocks until Ctrl+C
    """
    
    def __init__(self, port: int = None):
        port = port or PROVIDER_PORTS['cybersource_legacy']
        # Use --log=stdout to get proper log output instead of ncurses UI
        super().__init__(["ngrok", "http", str(port), "--log=stdout"])
        self.port = port
        self.public_url = None
    
    def start(self):
        print(f"Starting ngrok tunnel to port {self.port}...")
        print("(Press Ctrl+C to stop)\n")
        return super().start()
    
    def stream_output(self):
        """Stream output and capture public URL."""
        url_pattern = re.compile(r'url=(https://[^\s]+)')
        url_found = False
        
        def on_line(line):
            nonlocal url_found
            
            if not url_found:
                match = url_pattern.search(line)
                if match:
                    self.public_url = match.group(1)
                    url_found = True
                    print("\n>>> ngrok tunnel established!")
                    print(f">>> Public URL: {self.public_url}")
                    print(f">>> Callback URL: {self.public_url}/callback/cybersource_legacy/")
                    print(">>>")
                    print(">>> Configure this URL in CyberSource Business Center:")
                    print(">>>   1. Log into https://ebctest.cybersource.com")
                    print(">>>   2. Go to your Secure Acceptance profile")
                    print(f">>>   3. Set callback URL to: {self.public_url}/callback/cybersource_legacy/")
                    print(">>>")
                    print(">>> Keep this running while testing.\n")
                    write_tunnel_settings(ngrok_url=self.public_url)
                    return True
            
            return False
        
        super().stream_output(on_line)


class TunnelGroup:
    """
    Run multiple tunnels concurrently.
    
    Usage:
        TunnelGroup(StripeTunnel(), NgrokTunnel()).start().wait()
    """
    
    def __init__(self, *tunnels: TunnelProcess):
        self.tunnels = tunnels
        self.threads = []
    
    def start(self):
        """Start all tunnels and their output streaming threads."""
        for tunnel in self.tunnels:
            tunnel.start()
            thread = threading.Thread(target=tunnel.stream_output, daemon=True)
            thread.start()
            self.threads.append(thread)
        return self
    
    def wait(self):
        """Wait for tunnels to exit or Ctrl+C."""
        try:
            while all(t.is_running() for t in self.tunnels):
                time.sleep(0.5)
        except KeyboardInterrupt:
            print("\n>>> Stopping all tunnels...")
        finally:
            for tunnel in self.tunnels:
                tunnel.stop()
