# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-18 16:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perma_payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpdateRequestResponse',
            fields=[
                ('response_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='perma_payments.Response')),
                ('update_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='update_request_response', to='perma_payments.UpdateRequest')),
            ],
            options={
                'abstract': False,
            },
            bases=('perma_payments.response',),
        ),
    ]
