# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-18 17:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perma_payments', '0002_updaterequestresponse'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriptionrequestresponse',
            old_name='subscription_request',
            new_name='related_request',
        ),
        migrations.RenameField(
            model_name='updaterequestresponse',
            old_name='update_request',
            new_name='related_request',
        ),
    ]
