# Generated by Django 4.2.21 on 2026-01-29 15:46

from django.db import migrations, models
import django.db.models.deletion


def migrate_payment_tokens(apps, schema_editor):
    """
    Migrate existing payment_token values from SubscriptionRequestResponse
    to SubscriptionAgreement.provider_data.
    
    Since all provider_data fields start empty (default=dict), we can safely
    update them with the payment_token from the related response.
    """
    SubscriptionAgreement = apps.get_model('perma_payments', 'SubscriptionAgreement')
    SubscriptionRequestResponse = apps.get_model('perma_payments', 'SubscriptionRequestResponse')
    
    for response in SubscriptionRequestResponse.objects.filter(payment_token__isnull=False).exclude(payment_token=''):
        SubscriptionAgreement.objects.filter(
            pk=response.related_request.subscription_agreement_id
        ).update(provider_data={'payment_token': response.payment_token})


def reverse_migrate_payment_tokens(apps, schema_editor):
    """
    Reverse migration - clear provider_data.
    """
    SubscriptionAgreement = apps.get_model('perma_payments', 'SubscriptionAgreement')
    SubscriptionAgreement.objects.update(provider_data={})


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('perma_payments', '0002_auto_20200817_1809'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalsubscriptionagreement',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical subscription agreement', 'verbose_name_plural': 'historical subscription agreements'},
        ),
        migrations.AddField(
            model_name='historicalsubscriptionagreement',
            name='payment_provider',
            field=models.CharField(choices=[('cybersource_legacy', 'cybersource_legacy'), ('cybersource_rest', 'cybersource_rest'), ('stripe', 'stripe')], db_index=True, default='cybersource_legacy', help_text='The payment provider managing this subscription', max_length=30),
        ),
        migrations.AddField(
            model_name='historicalsubscriptionagreement',
            name='provider_data',
            field=models.JSONField(blank=True, default=dict, help_text='Provider-specific identifiers (e.g., payment_token, customer_id, subscription_id)'),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='payment_provider',
            field=models.CharField(choices=[('cybersource_legacy', 'cybersource_legacy'), ('cybersource_rest', 'cybersource_rest'), ('stripe', 'stripe')], db_index=True, default='cybersource_legacy', help_text='The payment provider used for this purchase', max_length=30),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='provider_data',
            field=models.JSONField(blank=True, default=dict, help_text='Provider-specific identifiers'),
        ),
        migrations.AddField(
            model_name='subscriptionagreement',
            name='payment_provider',
            field=models.CharField(choices=[('cybersource_legacy', 'cybersource_legacy'), ('cybersource_rest', 'cybersource_rest'), ('stripe', 'stripe')], db_index=True, default='cybersource_legacy', help_text='The payment provider managing this subscription', max_length=30),
        ),
        migrations.AddField(
            model_name='subscriptionagreement',
            name='provider_data',
            field=models.JSONField(blank=True, default=dict, help_text='Provider-specific identifiers (e.g., payment_token, customer_id, subscription_id)'),
        ),
        migrations.AlterField(
            model_name='historicalsubscriptionagreement',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='outgoingtransaction',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='response',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype'),
        ),
        # Migrate existing payment tokens to provider_data
        migrations.RunPython(
            migrate_payment_tokens,
            reverse_migrate_payment_tokens,
        ),
    ]
