# Generated by Django 4.2.21 on 2026-02-04 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perma_payments', '0003_alter_historicalsubscriptionagreement_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchaserequestresponse',
            options={},
        ),
        migrations.AddIndex(
            model_name='purchaserequest',
            index=models.Index(fields=['customer_pk', 'customer_type'], name='pp_pr_custtype_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaserequestresponse',
            index=models.Index(condition=models.Q(('inform_perma', True), ('perma_acknowledged_at__isnull', True)), fields=['related_request'], name='pp_prr_unack_rel_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptionagreement',
            index=models.Index(condition=models.Q(('status__in', ['Current', 'Hold'])), fields=['customer_pk', 'customer_type', 'id'], name='pp_sa_stand_cust_id_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptionagreement',
            index=models.Index(condition=models.Q(('paid_through__isnull', False), ('status', 'Canceled')), fields=['customer_pk', 'customer_type', 'paid_through', 'id'], name='pp_sa_canc_paid_thr_idx'),
        ),
    ]
