# Generated by Django 4.2.21 on 2026-02-10 20:35

from django.db import migrations, models
import django.db.models.deletion
import perma_payments.models


class Migration(migrations.Migration):

    dependencies = [
        ('perma_payments', '0004_alter_purchaserequestresponse_options_and_more'),
    ]

    operations = [
        # Step 1a: Add reference_number fields as nullable (no default needed for existing rows)
        migrations.AddField(
            model_name='changerequest',
            name='reference_number',
            field=models.CharField(
                max_length=32,
                null=True,
                help_text="Unique ID for this change request."
            ),
        ),
        migrations.AddField(
            model_name='historicalsubscriptionagreement',
            name='payment_provider',
            field=models.CharField(choices=[('cybersource_legacy', 'cybersource_legacy'), ('cybersource_rest', 'cybersource_rest'), ('stripe', 'stripe')], db_index=True, default='cybersource_legacy', help_text='The payment provider managing this subscription', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalsubscriptionagreement',
            name='provider_data',
            field=models.JSONField(blank=True, default=dict, help_text='Provider-specific identifiers (e.g., payment_token, customer_id, subscription_id)'),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='payment_provider',
            field=models.CharField(choices=[('cybersource_legacy', 'cybersource_legacy'), ('cybersource_rest', 'cybersource_rest'), ('stripe', 'stripe')], db_index=True, default='cybersource_legacy', help_text='The payment provider managing this subscription', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='provider_data',
            field=models.JSONField(blank=True, default=dict, help_text='Provider-specific identifiers (e.g., payment_token, customer_id, subscription_id)'),
        ),
        migrations.AddField(
            model_name='subscriptionagreement',
            name='payment_provider',
            field=models.CharField(choices=[('cybersource_legacy', 'cybersource_legacy'), ('cybersource_rest', 'cybersource_rest'), ('stripe', 'stripe')], db_index=True, default='cybersource_legacy', help_text='The payment provider managing this subscription', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscriptionagreement',
            name='provider_data',
            field=models.JSONField(blank=True, default=dict, help_text='Provider-specific identifiers (e.g., payment_token, customer_id, subscription_id)'),
        ),
        # Step 1b: Add reference_number fields as nullable (no default needed for existing rows)
        migrations.AddField(
            model_name='updaterequest',
            name='reference_number',
            field=models.CharField(
                max_length=32,
                null=True,
                help_text="Unique ID for this update request."
            ),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='reference_number',
            field=models.CharField(default=perma_payments.models.generate_purchase_reference_number, help_text='Unique ID for this purchase.', max_length=32),
        ),
        migrations.AlterField(
            model_name='subscriptionrequest',
            name='reference_number',
            field=models.CharField(default=perma_payments.models.generate_subscription_reference_number, help_text='Unique ID for this subscription. Subsequent charges, automatically made by the payment provider on the recurring schedule, will all be associated with this reference number.', max_length=32),
        ),
        migrations.AlterField(
            model_name='subscriptionrequestresponse',
            name='payment_token',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        # Step 2: Populate existing rows from the associated subscription's reference_number
        migrations.RunSQL(
            sql="""
                UPDATE perma_payments_changerequest cr
                SET reference_number = sr.reference_number
                FROM perma_payments_subscriptionrequest sr
                WHERE cr.subscription_agreement_id = sr.subscription_agreement_id
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="""
                UPDATE perma_payments_updaterequest ur
                SET reference_number = sr.reference_number
                FROM perma_payments_subscriptionrequest sr
                WHERE ur.subscription_agreement_id = sr.subscription_agreement_id
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),

        # Step 3: Add the default for new entries and remove null=True
        migrations.AlterField(
            model_name='changerequest',
            name='reference_number',
            field=models.CharField(
                default=perma_payments.models.generate_change_reference_number,
                max_length=32,
                help_text="Unique ID for this change request."
            ),
        ),
        migrations.AlterField(
            model_name='updaterequest',
            name='reference_number',
            field=models.CharField(
                default=perma_payments.models.generate_update_reference_number,
                max_length=32,
                help_text="Unique ID for this update request."
            ),
        ),

        migrations.CreateModel(
            name='WebhookLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(db_index=True, help_text="Payment provider that sent this webhook (e.g., 'stripe')", max_length=30)),
                ('event_id', models.CharField(db_index=True, help_text="Provider's unique event ID (e.g., Stripe's evt_...)", max_length=255)),
                ('event_type', models.CharField(db_index=True, help_text="Event type (e.g., 'invoice.paid', 'customer.subscription.deleted')", max_length=100)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('processed', 'Processed'), ('ignored', 'Ignored'), ('unmatched', 'Unmatched'), ('error', 'Error')], default='processed', max_length=20)),
                ('status_message', models.TextField(blank=True, help_text='Human-readable description of processing result')),
                ('raw_event', models.BinaryField(help_text='The full webhook payload, encrypted')),
                ('encryption_key_id', models.IntegerField()),
                ('subscription_agreement', models.ForeignKey(blank=True, help_text='The SubscriptionAgreement this event relates to, if identifiable', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhook_logs', to='perma_payments.subscriptionagreement')),
            ],
            options={
                'indexes': [models.Index(fields=['provider', 'event_type'], name='perma_payme_provide_beb341_idx'), models.Index(fields=['processed_at'], name='perma_payme_process_800649_idx')],
                'unique_together': {('provider', 'event_id')},
            },
        ),
    ]
