# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-26 20:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('perma_payments', '0006_auto_20170926_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outgoingtransaction',
            name='request_datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
