# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-27 16:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perma_payments', '0013_auto_20181126_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsubscriptionagreement',
            name='current_frequency',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='historicalsubscriptionagreement',
            name='current_link_limit',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='historicalsubscriptionagreement',
            name='current_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionagreement',
            name='current_frequency',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionagreement',
            name='current_link_limit',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionagreement',
            name='current_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True),
        ),
    ]
